openapi: 3.0.0
info:
  title: AtechESB
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /SyncMessage:
    post:
      summary: ''
      operationId: post-SyncMessage
      responses:
        '200':
          description: OK
components:
  schemas: {}
